/*
 * generated by Xtext 2.25.0
 */
package robostar.robocert.textual.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RoboCertUiModule extends AbstractRoboCertUiModule {

	public RoboCertUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
