/*******************************************************************************
 * Copyright (c) 2022 University of York and others
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Alvaro Miyazawa and Pedro Ribeiro - initial definition in RoboChart
 *   Matt Windsor - port to RoboCert
 ******************************************************************************/

package robocalc.robocert.generator.tockcsp.core.tgt;

import circus.robocalc.robochart.Context;
import circus.robocalc.robochart.Variable;
import circus.robocalc.robochart.generator.csp.comp.timed.CTimedGeneratorUtils;
import circus.robocalc.robochart.generator.csp.comp.untimed.CMemoryGenerator;
import circus.robocalc.robochart.generator.csp.untimed.ExpressionGenerator;
import com.google.inject.Inject;
import java.util.stream.Stream;
import org.eclipse.emf.ecore.EObject;
import robocalc.robocert.generator.tockcsp.ll.csp.CSPStructureGenerator;
import robocalc.robocert.model.robocert.util.DefinitionResolver;

/**
 * Generates CSP-M for the bodies of collection targets.
 * <p>
 * Unlike component targets (for which we can just use the processes generated by the RoboChart
 * semantics), collection targets have to pry into what would usually be black-box definitions at
 * the RoboChart level.  This means we need to replicate the insides of those definitions here; as
 * such, this generator is heavily based on the generator used for RoboChart module and controller
 * processes.
 *
 * @param <E> type of target elements.
 * @param <C> type of contexts used for memory etc.
 * @author Matt Windsor
 */
public abstract class CollectionTargetBodyGenerator<E extends EObject, C extends Context> {

  @Inject
  protected CSPStructureGenerator csp;
  @Inject
  protected DefinitionResolver defResolve;
  @Inject
  protected CTimedGeneratorUtils gu;
  @Inject
  protected CMemoryGenerator memGen;
  @Inject
  protected ExpressionGenerator exprGen;

  /**
   * Generates CSP-M for a collection target.
   *
   * @param element the element of the target to generate.
   * @return CSP-M for the target definition.
   */
  public CharSequence generate(E element) {
    final var ctx = context(element);
    final var ns = namespace(element);

    final var innerBody = innerBody(ns, element, ctx);

    final var mem = memoryModule(ns, ctx);
    final var memSet = csp.enumeratedSet(memorySet(ns, element, ctx).toArray(CharSequence[]::new));
    final var body = csp.bins().genParallel(innerBody, memSet, mem);
    return handleTerminationAndOptimise(ns, wrapOuter(element, ctx, body));
  }

  /**
   * Gets the namespace of the target's element.
   *
   * @param element the element in question.
   * @return the target's element's namespace.
   */
  protected abstract String namespace(E element);

  /**
   * Gets the memory context of the target's element.
   *
   * @param element the element in question.
   * @return the target's element's memory context (itself for controllers, the platform for
   * modules).
   */
  protected abstract C context(E element);

  /**
   * Gets the variables of the target's components.
   *
   * @param element element of the target being generated.
   * @return a stream of generated references to the elements of components of the element.
   */
  protected abstract Stream<CharSequence> componentVars(E element);

  /**
   * Creates the inner body of the target.
   *
   * @param ns      namespace of the target being generated.
   * @param element element of the target being generated.
   * @param ctx     memory context of the target being generated.
   * @return CSP-M for the wrapped body.
   */
  protected abstract CharSequence innerBody(String ns, E element, C ctx);

  /**
   * Wraps the outer body of the target.
   *
   * @param element element of the target being generated.
   * @param ctx     memory context of the target being generated.
   * @param body    the outer body (eg, after parallelising with the memory).
   * @return CSP-M for the wrapped body.
   */
  protected abstract CharSequence wrapOuter(E element, C ctx, CharSequence body);

  /**
   * Calculates the memory synchronisation set for an in-module target.
   *
   * @param ns      namespace of the target being generated.
   * @param element element of the target being generated.
   * @param ctx     memory context of the target being generated.
   * @return the elements of the synchronisation set, to be fed into an enumerated set.
   */
  private Stream<CharSequence> memorySet(String ns, E element, C ctx) {
    final var locals = gu.allLocalVariables(ctx).stream().map(this::intSet);
    return Stream.concat(locals, componentVars(element)).map(v -> csp.namespaced(ns, v));
  }

  private CharSequence memoryModule(CharSequence ns, Context ctx) {
    // Assuming always optimised, eg adding dbisim.
    return csp.function("dbisim", csp.namespaced(ns, "Memory") + memGen.memoryInstantiation(ctx));
  }

  private CharSequence handleTerminationAndOptimise(CharSequence ns, CharSequence body) {
    final var cs = csp.sets();
    final var cb = csp.bins();

    final var terminate = cs.set(terminate(ns));
    final var terminated = cb.interrupt(csp.tuple(body), terminate, csp.skip());
    final var hidden = cb.hide(terminated, terminate);

    final var priorities = cs.list(csp.namespaced(ns, "visibleMemoryEvents"), cs.set("tock"));
    final var prioritised = csp.function("prioritise", hidden, priorities);
    return csp.function("sbisim", prioritised);
  }

  /**
   * Constructs a reference to the termination channel.
   *
   * @param ns the namespace of the target element.
   * @return the terminate channel (not in a set).
   */
  protected CharSequence terminate(CharSequence ns) {
    return csp.namespaced(ns, "terminate");
  }

  protected String intGet(Variable v) {
    return "get_" + gu.variableId(v);
  }

  protected String intSet(Variable v) {
    return "set_" + gu.variableId(v);
  }

  protected String extSet(Variable v) {
    return "set_EXT_" + gu.variableId(v);
  }
}
