/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.roboprop.prototype.ide;

import circus.robocalc.roboprop.prototype.RoboPropRuntimeModule;
import circus.robocalc.roboprop.prototype.RoboPropStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RoboPropIdeSetup extends RoboPropStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RoboPropRuntimeModule(), new RoboPropIdeModule()));
	}
	
}
