/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.roboprop.prototype.ide;


/**
 * Use this class to register ide components.
 */
public class RoboPropIdeModule extends AbstractRoboPropIdeModule {
}
