<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="robocert" nsURI="http://robocert.robocalc/" nsPrefix="robocert">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="robocalc.robocert.model"/>
    <details key="modelPluginID" value="robocalc.robocert.model"/>
    <details key="modelDirectory" value="/robocalc.robocert.model/src-gen"/>
    <details key="editDirectory" value="/robocalc.robocert.model.edit/src-gen"/>
    <details key="editorDirectory" value="/robocalc.robocert.model.editor/src-gen"/>
    <details key="testsDirectory" value="/robocalc.robocert.model.tests/src-gen"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="RAPackage" eSuperTypes="../../circus.robocalc.robochart/model/robochart.ecore#//BasicPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cspFragments" upperBound="-1"
        eType="#//CSPFragment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequences" upperBound="-1"
        eType="#//Sequence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assertions" upperBound="-1"
        eType="#//NamedAssertion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CSPFragment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contents" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subsequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" lowerBound="1" upperBound="-1"
        eType="#//SequenceStep" containment="true" eOpposite="#//SequenceStep/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="../../circus.robocalc.robochart/model/robochart.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Target" containment="true" eOpposite="#//Target/sequence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="world" lowerBound="1" eType="#//World"
        containment="true" eOpposite="#//World/sequence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Subsequence"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" abstract="true" eSuperTypes="../../circus.robocalc.robochart/model/robochart.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="World" eSuperTypes="#//Actor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequence" lowerBound="1"
        eType="#//Sequence" eOpposite="#//Sequence/world"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Target" abstract="true" eSuperTypes="#//Actor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequence" lowerBound="1"
        eType="#//Sequence" eOpposite="#//Sequence/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instantiation" lowerBound="1"
        eType="#//TargetInstantiation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RCModuleTarget" eSuperTypes="#//Target">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//RCModule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetInstantiation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constants" upperBound="-1"
        eType="#//ConstAssignment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstAssignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//Subsequence" eOpposite="#//Subsequence/steps"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gap" lowerBound="1" eType="#//SequenceGap"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//SequenceAction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceGap">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allowed" lowerBound="1"
        eType="#//GapMessageSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forbidden" lowerBound="1"
        eType="#//ExtensionalGapMessageSet" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GapMessageSet" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionalGapMessageSet" eSuperTypes="#//GapMessageSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" ordered="false"
        upperBound="-1" eType="#//GapMessageSpec" containment="true" eOpposite="#//GapMessageSpec/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniverseGapMessageSet" eSuperTypes="#//GapMessageSet"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceAction" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArrowAction" eSuperTypes="#//SequenceAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//ArrowMessageSpec"
        containment="true" eOpposite="#//ArrowMessageSpec/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopAction" eSuperTypes="../../circus.robocalc.robochart/model/robochart.ecore#//NamedElement #//SequenceAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Subsequence"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinalAction" eSuperTypes="#//SequenceAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="MessageSpec" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="topic" lowerBound="1" eType="#//MessageTopic"
        containment="true" eOpposite="#//MessageTopic/spec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//Actor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrowMessageSpec" eSuperTypes="#//MessageSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//ArrowAction" eOpposite="#//ArrowAction/body"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GapMessageSpec" eSuperTypes="#//MessageSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//ExtensionalGapMessageSet" eOpposite="#//ExtensionalGapMessageSet/messages"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageTopic" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="spec" lowerBound="1" eType="#//MessageSpec"
        eOpposite="#//MessageSpec/topic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventTopic" eSuperTypes="#//MessageTopic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationTopic" eSuperTypes="#//MessageTopic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//OperationSig"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedAssertion" eSuperTypes="../../circus.robocalc.robochart/model/robochart.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Assertion"
        containment="true" eOpposite="#//Assertion/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assertion" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//NamedAssertion" eOpposite="#//NamedAssertion/body"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceAssertion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequence" lowerBound="1"
        eType="#//Sequence"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNegated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//SequenceAssertionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instantiation" lowerBound="1"
        eType="#//TargetInstantiation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" lowerBound="1" eType="#//CSPModel"
        defaultValueLiteral="TICK_TOCK"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SequenceAssertionType">
    <eLiterals name="HOLDS"/>
    <eLiterals name="IS_OBSERVED" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CSPModel">
    <eLiterals name="TICK_TOCK"/>
    <eLiterals name="TRACES" value="1"/>
  </eClassifiers>
</ecore:EPackage>
