<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="robocert" nsURI="http://robocert.robocalc/" nsPrefix="robocert">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="robocalc.robocert.model"/>
    <details key="modelPluginID" value="robocalc.robocert.model"/>
    <details key="modelDirectory" value="/robocalc.robocert.model/src-gen"/>
    <details key="editDirectory" value="/robocalc.robocert.model.edit/src-gen"/>
    <details key="editorDirectory" value="/robocalc.robocert.model.editor/src-gen"/>
    <details key="testsDirectory" value="/robocalc.robocert.model.tests/src-gen"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="RAPackage" eSuperTypes="../../circus.robocalc.robochart/model/robochart.ecore#//BasicPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cspFragments" upperBound="-1"
        eType="#//CSPFragment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequenceGroups" upperBound="-1"
        eType="#//SequenceGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assertions" upperBound="-1"
        eType="#//Assertion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CSPFragment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contents" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceGroup" eSuperTypes="../../circus.robocalc.robochart/model/robochart.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Target" containment="true" eOpposite="#//Target/group"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="world" lowerBound="1" eType="#//World"
        containment="true" eOpposite="#//World/group"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messageSets" upperBound="-1"
        eType="#//NamedMessageSet" containment="true" eOpposite="#//NamedMessageSet/group"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequences" upperBound="-1"
        eType="#//Sequence" containment="true" eOpposite="#//Sequence/group"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" lowerBound="2"
        upperBound="2" eType="#//Actor" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="../../circus.robocalc.robochart/model/robochart.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" lowerBound="1" eType="#//SequenceGroup"
        eOpposite="#//SequenceGroup/sequences"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Subsequence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Target" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="world" lowerBound="1" eType="#//World"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" lowerBound="2"
        upperBound="2" eType="#//Actor" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subsequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" lowerBound="1" upperBound="-1"
        eType="#//SequenceStep" containment="true" eOpposite="#//SequenceStep/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequence" eType="#//Sequence"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceStep" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//Subsequence" eOpposite="#//Subsequence/steps"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionStep" eSuperTypes="#//SequenceStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gap" lowerBound="1" eType="#//MessageSet"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//SequenceAction" containment="true" eOpposite="#//SequenceAction/step"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedMessageSet" eSuperTypes="../../circus.robocalc.robochart/model/robochart.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" eType="#//SequenceGroup"
        eOpposite="#//SequenceGroup/messageSets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="set" lowerBound="1" eType="#//MessageSet"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageSet" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="universal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefMessageSet" eSuperTypes="#//MessageSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="set" lowerBound="1" eType="#//NamedMessageSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionalMessageSet" eSuperTypes="#//MessageSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" ordered="false"
        upperBound="-1" eType="#//MessageSpec" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniverseMessageSet" eSuperTypes="#//MessageSet"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryMessageSet" eSuperTypes="#//MessageSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//MessageSet"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//BinarySetOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//MessageSet"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinarySetOperator">
    <eLiterals name="UNION"/>
    <eLiterals name="INTERSECTION" value="1"/>
    <eLiterals name="DIFFERENCE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anyGroup" eType="#//SequenceGroup"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="World" eSuperTypes="#//Actor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" lowerBound="1" eType="#//SequenceGroup"
        eOpposite="#//SequenceGroup/world"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Target" abstract="true" eSuperTypes="#//Actor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" lowerBound="1" eType="#//SequenceGroup"
        eOpposite="#//SequenceGroup/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instantiation" lowerBound="1"
        eType="#//TargetInstantiation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RCModuleTarget" eSuperTypes="#//Target">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//RCModule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetInstantiation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constants" upperBound="-1"
        eType="#//ConstAssignment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstAssignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StepWithBody" abstract="true" eSuperTypes="#//SequenceStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Subsequence"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeadlineStep" eSuperTypes="../../circus.robocalc.robochart/model/robochart.ecore#//NamedElement #//StepWithBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="units" lowerBound="1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopStep" eSuperTypes="../../circus.robocalc.robochart/model/robochart.ecore#//NamedElement #//StepWithBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bound" lowerBound="1" eType="#//LoopBound"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopBound" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfiniteLoopBound" eSuperTypes="#//LoopBound"/>
  <eClassifiers xsi:type="ecore:EClass" name="DefiniteLoopBound" eSuperTypes="#//LoopBound">
    <eStructuralFeatures xsi:type="ecore:EReference" name="times" lowerBound="1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LowerLoopBound" eSuperTypes="#//LoopBound">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowerTimes" lowerBound="1"
        eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeLoopBound" eSuperTypes="#//LoopBound">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowerTimes" lowerBound="1"
        eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperTimes" lowerBound="1"
        eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceAction" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="step" lowerBound="1" eType="#//ActionStep"
        eOpposite="#//ActionStep/action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrowAction" eSuperTypes="#//SequenceAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//MessageSpec"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinalAction" eSuperTypes="#//SequenceAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="WaitAction" eSuperTypes="#//SequenceAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="units" lowerBound="1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="topic" lowerBound="1" eType="#//MessageTopic"
        containment="true" eOpposite="#//MessageTopic/spec"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
        eType="#//MessageDirection" defaultValueLiteral="OUTBOUND"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//Argument" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Target" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//Actor"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//Actor"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageTopic" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="spec" lowerBound="1" eType="#//MessageSpec"
        eOpposite="#//MessageSpec/topic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventTopic" eSuperTypes="#//MessageTopic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationTopic" eSuperTypes="#//MessageTopic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//OperationSig"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessageDirection">
    <eLiterals name="INBOUND"/>
    <eLiterals name="OUTBOUND" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Argument" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionArgument" eSuperTypes="#//Argument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="ecore:EClass ../../circus.robocalc.robochart/model/robochart.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RestArgument" eSuperTypes="#//Argument"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assertion" abstract="true" eSuperTypes="../../circus.robocalc.robochart/model/robochart.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceAssertion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequence" lowerBound="1"
        eType="#//Sequence"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNegated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//SequenceAssertionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instantiation" lowerBound="1"
        eType="#//TargetInstantiation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" lowerBound="1" eType="#//CSPModel"
        defaultValueLiteral="TICK_TOCK"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SequenceAssertionType">
    <eLiterals name="HOLDS"/>
    <eLiterals name="IS_OBSERVED" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CSPModel">
    <eLiterals name="TICK_TOCK"/>
    <eLiterals name="TRACES" value="1"/>
  </eClassifiers>
</ecore:EPackage>
