/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.roboprop.prototype.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RoboPropUiModule extends AbstractRoboPropUiModule {

	public RoboPropUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
