/*
 * generated by Xtext 2.25.0
 */
package robostar.robocert.textual.ide;


/**
 * Use this class to register ide components.
 */
public class RoboCertIdeModule extends AbstractRoboCertIdeModule {
}
