package robocalc.robocert.generator.tockcsp.top;

import java.text.SimpleDateFormat;
import java.util.Date;

import com.google.inject.Inject;

import robocalc.robocert.generator.tockcsp.ll.CSPGroupGenerator;
import robocalc.robocert.generator.tockcsp.seq.SeqGroupGenerator;
import robocalc.robocert.generator.utils.UnsupportedSubclassHandler;
import robocalc.robocert.model.robocert.AssertionGroup;
import robocalc.robocert.model.robocert.CSPGroup;
import robocalc.robocert.model.robocert.CertPackage;
import robocalc.robocert.model.robocert.Group;
import robocalc.robocert.model.robocert.SequenceGroup;

/**
 * Top-level generator for tock-CSP.
 */
public class TopGenerator {
	@Inject
	private AssertionGroupGenerator ag;
	@Inject
	private CSPGroupGenerator cg;
	@Inject
	private SeqGroupGenerator sg;
	@Inject
	private ImportGenerator ig;
	@Inject
	private UnsupportedSubclassHandler ush;

	/**
	 * @return generated CSP for all elements.
	 *
	 * @param pkg the package being generated.
	 */
	public CharSequence generate(CertPackage pkg) {
		return String.join("\n\n", generateHeader(), ig.generateImports(pkg.eResource()), generateGroups(pkg));
	}

	/**
	 * Similar to CUntimedGenerator in RoboChart, and should probably include the
	 * version eventually too.
	 *
	 * @return the generated header.
	 */
	private CharSequence generateHeader() {
		return """
				--- generated by RoboCert
				--- on %s""".formatted(timestamp());
	}

	/**
	 * @return the current datetime as a human-readable timestamp.
	 */
	private String timestamp() {
		return new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(new Date());
	}

	/**
	 * @return included CSP for all groups.
	 *
	 * @param pkg the top-level package.
	 */
	private String generateGroups(CertPackage pkg) {
		return String.join("\n\n", pkg.getGroups().stream().map(this::generateGroup).toList());
	}

	private CharSequence generateGroup(Group it) {
		if (it instanceof CSPGroup c)
			return cg.generate(c);
		if (it instanceof SequenceGroup s)
			return sg.generate(s);
		if (it instanceof AssertionGroup a)
			return ag.generate(a);
		return ush.unsupported(it, "group", "");
	}

}
