/*
 * generated by Xtext 2.25.0
 */
package robocalc.robocert;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RoboCertStandaloneSetup extends RoboCertStandaloneSetupGenerated {

	public static void doSetup() {
		new RoboCertStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
