/*
 * generated by Xtext 2.25.0
 */
package robostar.robocert.textual.parser.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;
import robostar.robocert.textual.parser.antlr.internal.InternalRoboCertParser;

public class RoboCertTokenSource extends AbstractIndentationTokenSource {

	public RoboCertTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalRoboCertParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalRoboCertParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalRoboCertParser.RULE_END;
	}

}
