/*
 * generated by Xtext 2.25.0
 */
package robocalc.robocert.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import robocalc.robocert.RoboCertRuntimeModule;
import robocalc.robocert.RoboCertStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RoboCertIdeSetup extends RoboCertStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RoboCertRuntimeModule(), new RoboCertIdeModule()));
	}
	
}
