/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.roboprop.prototype;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RoboPropStandaloneSetup extends RoboPropStandaloneSetupGenerated {

	public static void doSetup() {
		new RoboPropStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
