/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.roboprop.prototype;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RoboPropRuntimeModule extends AbstractRoboPropRuntimeModule {
}
